version: '3'

services:

  db:
    image: mysql:8.0
    command: mysqld --user=mysql --innodb-use-native-aio=0
    env_file:
      - ./env/production/.env
    volumes:
      - ./db-datadir:/var/lib/mysql
      - ./sql:/docker-entrypoint-initdb.d
    ports:
      - '3306:3306'
    tty: true

  web:
    build:
      context: ./
      dockerfile: Dockerfile-production
    container_name: c4c
    command: bash -c "python manage.py collectstatic --noinput && gunicorn config.wsgi -b 0.0.0.0:8000"
    env_file:
      - ./env/production/.env
    volumes:
      - .:/code
      - ./static:/code/static
    expose:
      - '8000'
    depends_on:
      - db
