version: '3'

services:

  db:
    image: mysql:8.0
    command: mysqld --user=mysql --innodb-use-native-aio=0
    env_file:
      - ./env/production/.env
    volumes:
      - ./db-datadir:/var/lib/mysql
      - ./sql:/docker-entrypoint-initdb.d
    ports:
      - "3306:3306"
    tty: true

  web:
    build:
      context: ./
      dockerfile: Dockerfile-production
    command: gunicorn config.wsgi
    env_file:
      - ./env/production/.env
    volumes:
      - .:/code
      - ./static:/static
    expose:
      - "8001"
    depends_on:
      - db

  nginx:
    image: nginx:1.15
    ports:
      - "8000:8000"
    volumes:
      - ./nginx/conf:/etc/nginx/conf.d
#      - ./nginx/uwsgi_params:/etc/nginx/uwsgi_params
      - ./static:/static
    depends_on:
      - web
