version: '3'

services:

  db:
    image: mysql:8.0
    command: mysqld --user=mysql --innodb-use-native-aio=0
    env_file:
      - ./env/production/.env
    volumes:
      - ./db-datadir:/var/lib/mysql
      - ./sql:/docker-entrypoint-initdb.d
    ports:
      - "3306:3306"
    tty: true

  web:
    build:
      context: ./
      dockerfile: Dockerfile-production
    command: gunicorn config.wsgi -b 0.0.0.0:8080 --forwarded-allow-ips="*"
    env_file:
      - ./env/production/.env
    volumes:
      - .:/code
      - ./static:/code/static
    expose:
      - "8080"
    depends_on:
      - db

  https-portal:
    image: steveltn/https-portal:1
    ports:
      - '8080:80'
      - '443:443'
    restart: always
    environment:
      DOMAINS: 'kaizumaki.net -> http://web:8080'
#      STAGE: 'production'
#      FORCE_RENEW: 'true'
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./ssl-certs:/var/lib/https-portal
      - ./static:/var/www/vhosts/kaizumaki.net/static
    depends_on:
      - web

#  nginx:
#    restart: always
#    image: nginx:1.15
#    ports:
#      - "80:80"
#    volumes:
#      - ./nginx:/etc/nginx
#      - ./static:/var/www/html/static
#    depends_on:
#      - web

#volumes:
#  ssl-certs:
#  static:
