FROM python:3.7
ENV PYTHONUNBUFFERED 1
RUN mkdir /code
WORKDIR /code
ADD ./requirements/base.txt /code/
ADD ./requirements/production.txt /code/
RUN pip install --upgrade pip
RUN pip install -r production.txt
ADD . /code/
