# Generated by Django 2.1.2 on 2018-10-30 10:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dialogue', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answer',
            old_name='question',
            new_name='question_id',
        ),
        migrations.RenameField(
            model_name='keyword',
            old_name='answer',
            new_name='answer_id',
        ),
    ]
