# Generated by Django 2.1.3 on 2018-11-10 06:34

from django.db import migrations, models
import django_mysql.models


class Migration(migrations.Migration):

    dependencies = [
        ('dialogue', '0002_auto_20181109_2027'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='answer_temp_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='keyword',
            name='answer_temp_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='keyword',
            name='keyword_temp_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='answer',
            name='answer_text',
            field=django_mysql.models.ListTextField(models.CharField(max_length=255), size=255),
        ),
    ]
