# Generated by Django 2.1.3 on 2018-11-10 14:21

from django.db import migrations, models
import django_mysql.models


class Migration(migrations.Migration):

    dependencies = [
        ('dialogue', '0004_auto_20181110_2228'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='answer_text',
            field=django_mysql.models.ListTextField(models.CharField(max_length=255), size=255),
        ),
    ]
