# Generated by Django 2.1.2 on 2018-10-30 11:56

from django.db import migrations, models
import django_mysql.models


class Migration(migrations.Migration):

    dependencies = [
        ('dialogue', '0006_auto_20181030_2027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='answer_text',
            field=django_mysql.models.ListTextField(models.CharField(max_length=255), size=10),
        ),
    ]
