# Generated by Django 2.1.3 on 2018-11-10 14:54

from django.db import migrations
import django_mysql.models


class Migration(migrations.Migration):

    dependencies = [
        ('dialogue', '0007_auto_20181110_2348'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='answer_text',
            field=django_mysql.models.JSONField(default=list),
        ),
    ]
