# Generated by Django 2.1.2 on 2018-10-30 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dialogue', '0007_auto_20181030_2056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='answer_text',
            field=models.TextField(),
        ),
    ]
