# Generated by Django 2.1.3 on 2018-11-10 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dialogue', '0008_auto_20181110_2354'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answer',
            old_name='answer_text',
            new_name='answer_texts',
        ),
    ]
