# Generated by Django 2.1.3 on 2018-11-17 07:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dialogue', '0009_auto_20181111_0002'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='parent_id',
            new_name='parent_answer_id',
        ),
    ]
