# Generated by Django 2.1.2 on 2018-11-01 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dialogue', '0009_auto_20181030_2146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='answer_id',
            field=models.AutoField(db_column='ANSWER ID', primary_key=True, serialize=False),
        ),
    ]
