# Generated by Django 2.1.2 on 2018-11-01 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dialogue', '0010_auto_20181102_0433'),
    ]

    operations = [
        migrations.AlterField(
            model_name='keyword',
            name='keyword_id',
            field=models.AutoField(db_column='KEYWORD ID', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_id',
            field=models.AutoField(db_column='QUESTION ID', primary_key=True, serialize=False),
        ),
    ]
