# Generated by Django 2.1.2 on 2018-11-01 20:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dialogue', '0012_auto_20181102_0518'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='author',
        ),
    ]
