# Generated by Django 2.1.2 on 2018-11-01 20:41

from django.db import migrations, models
import django_mysql.models


class Migration(migrations.Migration):

    dependencies = [
        ('dialogue', '0013_remove_question_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='answer_text',
            field=django_mysql.models.ListTextField(models.CharField(max_length=255), size=10),
        ),
    ]
