# Generated by Django 2.1.2 on 2018-11-01 20:42

from django.db import migrations, models
import django_mysql.models


class Migration(migrations.Migration):

    dependencies = [
        ('dialogue', '0014_auto_20181102_0541'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='answer_text',
            field=django_mysql.models.ListTextField(models.CharField(blank=True, max_length=255, null=True), size=10),
        ),
    ]
