# Generated by Django 2.1.2 on 2018-11-02 02:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dialogue', '0016_auto_20181102_0543'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answer',
            old_name='answer_text',
            new_name='answer_texts',
        ),
    ]
